os: osx
osx_image: xcode11.3
language: swift
before_script:
- agvtool new-version -all $(date +'%Y.%m.%d.%H.%M')
before_install:
- gem install xcpretty
- gem install cocoapods -v '0.32.1'
install:
- rm -f Podfile.lock
- travis_wait 10 pod install --silent
script:
- xcodebuild -scheme Analyser -workspace Analyser.xcworkspace -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 8 Plus,OS=13.2.2' | xcpretty -s && exit ${PIPESTATUS[0]}
after_success:
- gem install jazzy
- make documentation
- pwd
- ls -al
deploy:
provider: pages
skip-cleanup: true
github-token: $GH_TOKEN
local-dir: docs
on:
branch: master
